export const questions = [
  {
    id: 1,
    que: 'Get me count of distinct values in dataset',
    key: ['distinct', 'dataset'],
    ansHead: 'distinct values in dataset',
    ans: [
      { dimension: 'Date', data: 365 },
      { dimension: 'Rented Bike Count', data: 2166 },
      { dimension: 'Hour', data: 24 },
      { dimension: 'Temperature(°C)', data: 546 },
      { dimension: 'Humidity(%)', data: 90 },
      { dimension: 'Wind speed (m/s)', data: 65 },
      { dimension: 'Visibility (10m)', data: 365 },
      { dimension: 'Dew point temperature(°C)', data: 1789 },
      { dimension: 'Solar Radiation (MJ/m2)', data: 556 },
      { dimension: 'Rainfall(mm)', data: 61 },
      { dimension: 'Snowfall (cm)', data: 51 },
      { dimension: 'Seasons', data: 4 },
      { dimension: 'Holiday', data: 2 },
      { dimension: 'Functioning Day', data: 2 },
    ],
  },
  {
    id: 2,
    que: 'Get me count of distinct values in column Hour',
    key: ['distinct', 'hour'],
    ansHead: 'distinct values in Hour column',
    ans: [
      { dimension: 'Hour', data: 24 },
    ],
  },
  {
    id: 3,
    que: 'Get me count of unique Seasons',
    key: ['unique', 'season'],
    ansHead: 'count of unique Seasons',
    ans: [
      { dimension: 'Seasons', data: 4 },
    ],
  },
  {
    id: 4,
    que: 'Get me distint values in Holiday',
    key: ['distint', 'holiday'],
    ansHead: 'distinct values in holiday',
    ans: [
      { dimension: 'holiday', data: 4 },
    ],
  },
  {
    id: 5,
    que: 'what are outliers in Rainfall',
    key: ['outliers', 'rainfall'],
    ansHead: 'outliers in Rainfall',
    ans: [
      { dimension: 51, data: 0.5 },
      { dimension: 54, data: 1 },
      { dimension: 57, data: 2.5 },
      { dimension: 78, data: 0.1 },
      { dimension: 120, data: 0.1 },
      { dimension: '...', data: '...' },
      { dimension: 8241, data: 0.5 },
      { dimension: 8520, data: 0.2 },
      { dimension: 8523, data: 1.0 },
      { dimension: 8601, data: 9.1 },
      { dimension: 8604, data: 1.8 },
    ],
  },
  {
    id: 6,
    que: 'what is correlation between Rainfall and Temperature',
    key: ['correlation'],
    ansHead: 'correlation between Rainfall and Temperature',
    ans: [
      { dimension: 'Correlation', data: 0.05028185850466923 },
    ],
  },
  {
    id: 7,
    que: 'Get count of missing values ',
    key: ['missing'],
    ansHead: 'missing values ',
    ans: [
      { dimension: 'Date', data: 0 },
      { dimension: 'Rented Bike Count', data: 0 },
      { dimension: 'Hour', data: 0 },
      { dimension: 'Temperature(°C)', data: 0 },
      { dimension: 'Humidity(%)', data: 0 },
      { dimension: 'Wind speed (m/s)', data: 0 },
      { dimension: 'Visibility (10m)', data: 0 },
      { dimension: 'Dew point temperature(°C)', data: 0 },
      { dimension: 'Solar Radiation (MJ/m2)', data: 0 },
      { dimension: 'Rainfall(mm)', data: 0 },
      { dimension: 'Snowfall (cm)', data: 0 },
      { dimension: 'Seasons', data: 0 },
      { dimension: 'Holiday', data: 0 },
      { dimension: 'Functioning Day', data: 0 },
    ],
  },
  {
    id: 8,
    que: 'find maximum Rainfall obtained',
    key: ['maximum', 'rainfall'],
    ansHead: 'maximum Rainfall',
    ans: [
      { dimension: 'Maximum Rainfall', data: 35 },
    ],
  },
  {
    id: 9,
    que: 'Find average Temperature',
    key: ['average'],
    ansHead: 'average Temperature',
    ans: [
      { dimension: 'Average Temperature', data: 12.88 },
    ],
  },
  {
    id: 10,
    que: 'Find the maximum Rented Bike Count in a day',
    key: ['maximum', 'rented bike'],
    ansHead: 'Count of maximum Rented Bike',
    ans: [
      { dimension: 'Rented Bike', data: 3566 },
    ],
  },
  {
    id: 11,
    que: 'Find the minimum Rented Bike count in a day',
    key: ['minimum'],
    ansHead: 'Count of minimum Rented Bike',
    ans: [
      { dimension: 'Rented Bike', data: 0 },
    ],
  },
  {
    id: 12,
    que: 'Find median humidity',
    key: ['median'],
    ansHead: 'median humidity',
    ans: [
      { dimension: 'Humidity(%)', data: 57.0 },
    ],
  },
  {
    id: 13,
    que: 'Find mode of visibility',
    key: ['mode'],
    ansHead: 'mode of visibility',
    ans: [
      { dimension: 'Visibility (10m)', data: 2000 },
    ],
  },

];
